/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        forest: {
          DEFAULT: '#1F4D3A',
          dark: '#16382A',
          light: '#EDF4F0',
          hover: '#28624A',
          muted: '#2D664E',
        },
        cream: {
          DEFAULT: '#F6F2E8',
          light: '#FAF8F3',
          dark: '#EBE5D6',
        },
        charcoal: {
          DEFAULT: '#181E1B',
          muted: '#4A5550',
          subtle: '#6B7280',
        },
        sprout: {
          dark: '#0F2A1D',
          green: '#1F5C3F',
          muted: '#5F6F66',
        },
        // Verifier MRV Console Enterprise Palette
        primary: {
          DEFAULT: '#003b1b',
          container: '#14532d',
          fixed: '#b1f2be',
          'fixed-dim': '#96d5a3',
        },
        secondary: {
          DEFAULT: '#3a6753',
          container: '#bceed3',
          fixed: '#bceed3',
          'fixed-dim': '#a1d1b8',
        },
        tertiary: {
          DEFAULT: '#003a25',
          container: '#005337',
          fixed: '#6ffbbe',
          'fixed-dim': '#4edea3',
        },
        'on-primary': '#ffffff',
        'on-secondary': '#ffffff',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#39ce94',
        'on-secondary-container': '#406d58',
        'on-surface': '#131b2e',
        'on-surface-variant': '#404941',
        'bg-canvas': '#F4F7F4',
        'bg-canvas-cream': '#F9FAF7',
        'surface-white': '#FFFFFF',
        'surface-sidebar': '#14532D',
        'surface-sidebar-active': '#1F4D3A',
        'surface-container': '#eaedff',
        'surface-container-low': '#f2f3ff',
        'surface-container-high': '#e2e7ff',
        'status-verified-bg': '#D1FAE5',
        'status-verified-text': '#065F46',
        'status-pending-bg': '#FEF3C7',
        'status-pending-text': '#B45309',
        'status-rejected-bg': '#FEE2E2',
        'status-rejected-text': '#B91C1C',
        'status-listed-bg': '#DBEAFE',
        'status-listed-text': '#1E40AF',
        'accent-warning': '#F59E0B',
        'accent-danger': '#EF4444',
        outline: '#717970',
        'outline-variant': '#c0c9be',
        'border-subtle': '#E2E8F0',
        'border-medium': '#CBD5E1',
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
        'space-2xl': '3rem',
        gutter: '1.5rem',
      },
      fontFamily: {
        serif: ['"Instrument Serif"', 'Georgia', 'serif'],
        sans: ['Inter', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '4px',
        sm: '2px',
        md: '4px',
        lg: '6px',
        xl: '0.5rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
